--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 05/07/2019 1:12:02
-- Server version: 5.5.5-10.1.32-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS academianoelia;

CREATE DATABASE IF NOT EXISTS academianoelia
CHARACTER SET utf8
COLLATE utf8_spanish2_ci;

--
-- Set default database
--
USE academianoelia;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(128) NOT NULL,
  password varchar(128) NOT NULL,
  email varchar(128) NOT NULL,
  authKey varchar(128) NOT NULL,
  activate tinyint(1) NOT NULL DEFAULT 0,
  accessToken varchar(180) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_spanish2_ci;

--
-- Create table `profesores`
--
CREATE TABLE IF NOT EXISTS profesores (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  apellidos varchar(100) NOT NULL,
  direccion varchar(200) NOT NULL,
  nif varchar(9) NOT NULL,
  nacimiento date NOT NULL,
  alta date NOT NULL,
  baja date NOT NULL,
  movil varchar(20) NOT NULL,
  mail varchar(100) NOT NULL,
  observaciones text NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `migrations`
--
CREATE TABLE IF NOT EXISTS migrations (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration varchar(255) NOT NULL,
  batch int(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `cursos`
--
CREATE TABLE IF NOT EXISTS cursos (
  id_cur int(11) NOT NULL AUTO_INCREMENT,
  referencia varchar(50) NOT NULL,
  descripcion text NOT NULL,
  PRIMARY KEY (id_cur)
)
ENGINE = INNODB,
AUTO_INCREMENT = 13,
AVG_ROW_LENGTH = 1365,
CHARACTER SET utf8,
COLLATE utf8_spanish2_ci;

--
-- Create table `asignaturas`
--
CREATE TABLE IF NOT EXISTS asignaturas (
  id_as int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  descripcion text NOT NULL,
  PRIMARY KEY (id_as)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_spanish2_ci;

--
-- Create table `alumnos`
--
CREATE TABLE IF NOT EXISTS alumnos (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  apellidos varchar(100) NOT NULL,
  direccion varchar(200) NOT NULL,
  NIF varchar(9) NOT NULL,
  nacimiento date NOT NULL,
  movil varchar(20) NOT NULL,
  mail varchar(100) NOT NULL,
  observaciones text NOT NULL,
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  alta date NOT NULL,
  baja date DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Robert', 'Robert', 'robherblanc@outlook.com', '1234', 1, '');

-- 
-- Dumping data for table profesores
--
INSERT INTO profesores VALUES
(1, 'Fernando', ' López Fernandez', 'Bº de Abajo', '13258125A', '0000-00-00', '0000-00-00', '0000-00-00', '665124562', 'fdolopezmarti@gmail.com', 'Clases de Matematicas los lunes, miercoles y viernes', NULL, NULL);

-- 
-- Dumping data for table migrations
--
INSERT INTO migrations VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_04_28_235947_create_alumnos_table', 1),
(4, '2019_04_29_001441_create_clases_table', 2),
(5, '2019_04_29_001545_create_profesores_table', 2);

-- 
-- Dumping data for table cursos
--
INSERT INTO cursos VALUES
(1, '1ESO', 'PRIMER CURSO DE LA ESO'),
(2, '2ESO', 'SEGUNDO CURSO DE LA ESO'),
(3, '3ESO', 'TERCER CURSO DE LA ESO'),
(4, '4ESO', 'CUARTO CURSO DE LA ESO'),
(5, '1PRIMA', 'PRIMERO DE PRIMARIA'),
(6, '2PRIMA', 'SEGUNDO DE PRIMARIA'),
(7, '3PRIMA', 'TERCERO DE PRIMARIA'),
(8, '4PRIMA', 'CUARTO DE PRIMARIA'),
(9, '5PRIMA', 'QUINTO DE PRIMARIA'),
(10, '6PRIMA', 'SEXTO DE PRIMARIA'),
(11, '1BACHI', 'PRIMERO DE BACHILLER'),
(12, '2BACHI', 'SEGUNDO DE BACHILLER');

-- 
-- Dumping data for table asignaturas
--
INSERT INTO asignaturas VALUES
(1, 'CIENCIAS DE LA NATURALEZA', 'CIENCIAS NATURALES'),
(2, 'CIENCIAS SOCIALES', 'CIENCIAS SOCIALES'),
(3, 'LENGUA CASTELLANA Y LITERATURA', 'LENGUA'),
(4, 'MATEMATICAS', 'MATEMATICAS'),
(5, 'LENGUA EXTRANJERA', 'IDIOMAS');

-- 
-- Dumping data for table alumnos
--
INSERT INTO alumnos VALUES
(1, 'Pepito', 'Perez', 'c/Alta 60 5b', '', '1973-07-09', '667743229', 'robherblanc@outlook.com', 'Prueba 2', '2019-04-29 00:56:56', '2019-04-29 01:06:25', '2019-05-01', NULL),
(2, 'Roberto', 'Hernandez Blanco', 'Bº DE LA TEJA 87', '20195088F', '0000-00-00', '667743229', 'robherblanc@outlook.com', 'Ninguna', NULL, NULL, '0000-00-00', NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;